import Head from 'next/head'
import Form from '../Components/Form'

export default function Home() {
    return (
        <div className="relative w-full overflow-hidden  py-2 h-[90vh]">
            <Head>
                <title>GPA Calc</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/flavicon.png" />
            </Head>

            <main className="relative pl-4 pb-24  lg:pl-16">
                <div>
                    <Form />
                </div>
            </main>
        </div>
    )
}
